# Generated by Django 5.0.7 on 2024-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('reference_number', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='inverter',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
