# Generated by Django 5.0.7 on 2024-07-29 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_potentialcustomers_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialcustomers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
