# Generated by Django 5.0.7 on 2024-08-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0005_variablecosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='default_choice',
            field=models.BooleanField(default=False),
        ),
    ]
