# Generated by Django 5.0.2 on 2024-11-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0006_panel_default_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=10)),
                ('SystemRange', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='potentialcustomers',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
